const DEMO_CSV_DATA = [
  ['New attendee,Name,Role,Tutorial,Note,Skills'],
  ['false,Adrian Awesome (he),Student,Other,"",N/A'],
  ['false,Bella Bright (She),Student,React Project,I need help understanding components and structure of the design,N/A'],
  ['false,Carl Cheerful (He),Student,Python,"",N/A'],
  ['false,Diana Delightful,Coach,N/A,"","Full-Stack JavaScript, functional programming, Game Development, java, python, distributed systems"'],
  ['false,Ethan Excellent (He),Coach,N/A,"","javascript, TypeScript, nodejs, ReactJS, Nextjs, python"'],
  ['true,Fiona Fabulous (she/her),Coach,N/A,"","html, css, javascript, node, React, Next.js, react-router, Redux, TypeScript, styled-components, GraphQL"'],
  ['false,Gabriel Giggly (he/him),Student,React Project,"",N/A'],
  ['false,Hannah Happy (She),Coach,N/A,"Java, python, data science, backend ","java, python, SQL, nosql, web, c, Linux, rust"'],
  ['false,Isaac Incredible (He/him),Student,Other,C#,N/A'],
  ['false,Jessica Jolly,Student,Java,"",N/A'],
  ['false,Kevin Kind (he/him/his),Coach,N/A,Junior software developer with experience with JavaScript/TypeScript,"javascript, React, Express, back-end, Front-end"'],
  ['false,Luna Lovely (she),Coach,N/A,"Python, Testing, Spark/Databricks/Data or can do most beginner stuff ",""'],
  ['false,Marcus Magnificent (He),Coach,N/A,"I am an android developer in Lloyds bank, knows Java, Kotlin and backend.","Android, java, Spring Boot, AWS, MySql, Angular, Ionic, kotlin"'],
  ['false,Nina Nimble (she/her),Student,Python,"",N/A'],
  ['false,"Oliver Optimistic (he, him)",Coach,N/A,"","Go, javascript, ruby, algorithms"'],
  ['false,Petra Playful (she),Coach,N/A,"",javascript'],
  ['false,Quinn Quirky (he),Student,React Project,changes not reflected on the deployed version,N/A'],
  ['false,Sophie Sparkling (She/her),Coach,N/A,"Happy to help any and all Java and JS projects, failing that just ask good questions.","java, javascript, ReactJS, SQL"'],
  ['false,Tyler Terrific (he/him),Student,Python,I\'d like help understanding classes and OOPs intuitively ,N/A'],
  ['false,Rosa Radiant,Coach,N/A,I specify in React on frontends and NodeJS on the backend,"html, css, javascript, React, node, REST, GraphQL, Git, Jest, Cypress, mocha, MonoDB, tailwind"'],
  ['true,Uma Unstoppable (she/her),Student,"I don\'t know, I\'m a complete beginner.","",N/A'],
  ['false,Victor Vibrant (He/Him),Student,"I don\'t know, I\'m a complete beginner.",First time coming to a codebar workshop so I\'m excited to join :),N/A'],
  ['false,Willow Wonderful,Student,Python,understanding API (for SQL server and for LLM),N/A'],
  ['false,Xander Xtraordinary (him),Coach,N/A,"","javascript/typescript, React, Remix.js/Next.js, HTML/CSS, version control"'],
  ['false,Yvonne Youthful,Student,Java,Java spring boot project ,N/A'],
  ['false,Zara Zippy (she/her),Student,React Project,"",N/A'],
];
